# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tomba < Formula
  desc "CLI utility to search or verify lists of email addresses in minutes."
  homepage "https://tomba.io"
  version "v1.0.3-next"
  license "Apache-2.0"

  depends_on "git"
  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tomba-io/tomba/releases/download/v1.0.3/tomba_darwin_amd64.tar.gz"
      sha256 "445dac0a1617ecb33cb3ba6aedb47302ce93e514e2b20a0ebfa098cd566d41a4"

      def install
        bin.install "tomba"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tomba-io/tomba/releases/download/v1.0.3/tomba_darwin_arm64.tar.gz"
      sha256 "413f8d3c96dd64015e0bf4bd16ab989551e2c1d868de6510f8e35e86db7c1f56"

      def install
        bin.install "tomba"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tomba-io/tomba/releases/download/v1.0.3/tomba_linux_arm64.tar.gz"
      sha256 "fe45b3933610043afad4d609e7bce064aa396353cbdd40a7037a0fcdf404192f"

      def install
        bin.install "tomba"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tomba-io/tomba/releases/download/v1.0.3/tomba_linux_amd64.tar.gz"
      sha256 "15b3b31340a796126e80edcf3b8e2944c9d81af881859121f1026ec69b3ece28"

      def install
        bin.install "tomba"
      end
    end
  end

  test do
    system "#{bin}/tomba version"
  end
end
